# Generated by Django 5.2.8 on 2025-11-15 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_producto_nombre_imagenproducto_resena'),
    ]

    operations = [
    ]
