# Generated by Django 5.2.8 on 2025-11-16 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_producto_imagen_producto_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('metodo', models.CharField(default='simulado', max_length=50)),
                ('aprobado', models.BooleanField(default=False)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tienda.orden')),
            ],
        ),
    ]
